FROM node:14-alpine3.14 AS builder

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install \
    && npm i -D typescript@4.5.5

COPY . .

LABEL maintainer="Trisoft <code@trisoft.co.in>"

RUN ["npx","ng","build","--configuration=production","--progress"]

FROM nginx:1.21-alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/super-admin-panel-build /usr/share/nginx/html
